In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('data_county.csv', index_col=0)
data

country    capital    area  populasi
BR        Brazil  Brazillia   8.516    200.40
RU         Rusia     Moscow  17.100    143.50
IN         India  New Dehli   3.286   1252.00
CH         China     Bejing   9.597   1357.00
SA  South Africa   Pretoria   1.221     52.98

In [3]:
# selecet data
# terdapat kesalahan karena pandas array 1 D
data['country']

BR          Brazil
RU           Rusia
IN           India
CH           China
SA    South Africa
Name: country, dtype: object

In [4]:
# memperbaiki kesalahan menggunakan double [[]]
data[['country']]

country
BR        Brazil
RU         Rusia
IN         India
CH         China
SA  South Africa

In [6]:
# menampilkan data perkolom
data[['country', 'area', 'populasi']]

country    area  populasi
BR        Brazil   8.516    200.40
RU         Rusia  17.100    143.50
IN         India   3.286   1252.00
CH         China   9.597   1357.00
SA  South Africa   1.221     52.98

In [7]:
# menampilkan data perbaris
data[1:4]

country    capital    area  populasi
RU   Rusia     Moscow  17.100     143.5
IN   India  New Dehli   3.286    1252.0
CH   China     Bejing   9.597    1357.0

In [9]:
# menampilkan baris menggunakan loc = label
# menggunakan double square bracker [[]]
data.loc[['RU']]

country capital  area  populasi
RU   Rusia  Moscow  17.1     143.5

In [10]:
# menampilkan beberapa baris selected menggunakan loc
data.loc[['RU', 'IN', 'CH']]

country    capital    area  populasi
RU   Rusia     Moscow  17.100     143.5
IN   India  New Dehli   3.286    1252.0
CH   China     Bejing   9.597    1357.0

In [11]:
# menampilakan baris dan kolom selected menggunakan loc
data.loc[['RU', 'IN', 'CH'], ['country', 'area', 'populasi']]

country    area  populasi
RU   Rusia  17.100     143.5
IN   India   3.286    1252.0
CH   China   9.597    1357.0

In [33]:
# menampilkan baris dengan range dan kolom selected iloc
data.loc['RU':'CH', ['country', 'area', 'populasi']]

country    area  populasi
RU   Rusia  17.100     143.5
IN   India   3.286    1252.0
CH   China   9.597    1357.0

In [35]:
# menampilakn baris selected dengan kolom range loc
data.loc[['RU', 'IN', 'CH'], 'country':'area']

country    capital    area
RU   Rusia     Moscow  17.100
IN   India  New Dehli   3.286
CH   China     Bejing   9.597

In [14]:
# menampilkan baris menggunakan iloc
data.iloc[[1]]

country capital  area  populasi
RU   Rusia  Moscow  17.1     143.5

In [15]:
# menampilkan baris selected menggunakan iloc
data.iloc[[1,2,3]]

country    capital    area  populasi
RU   Rusia     Moscow  17.100     143.5
IN   India  New Dehli   3.286    1252.0
CH   China     Bejing   9.597    1357.0

In [18]:
# menampilkan baris dan kolom menggunakan iloc
data.iloc[[1,2,3],[0,2,3]]

country    area  populasi
RU   Rusia  17.100     143.5
IN   India   3.286    1252.0
CH   China   9.597    1357.0

In [25]:
# menampilkan baris dengan range dan kolom selected iloc
data.iloc[1:4, [0,2,3]]

country    area  populasi
RU   Rusia  17.100     143.5
IN   India   3.286    1252.0
CH   China   9.597    1357.0

In [26]:
# menampilakn baris selected dengan kolom range iloc
data.iloc[[1,2,3], 0:3]

country    capital    area
RU   Rusia     Moscow  17.100
IN   India  New Dehli   3.286
CH   China     Bejing   9.597

In [4]:
import numpy as np

In [5]:
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79], [65.4, 59.2, 63.8, 88.4, 68.71]])
np_2d

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.2 , 63.8 , 88.4 , 68.71]])

In [70]:
# selected array row 1
np_2d[0,:]

array([1.73, 1.68, 1.71, 1.89, 1.79])

In [72]:
# selected array row 2
np_2d[1,:]

array([65.4 , 59.2 , 63.8 , 88.4 , 68.71])

In [48]:
# selected array row 1 kolom 3 & 4
np_2d[0,[2,3]]

array([1.71, 1.89])

In [76]:
# selected array kolom 2 row 1 & 2
np_2d[[0,1],1]

array([ 1.68, 59.2 ])

In [88]:
# customization index 2 x 2 dimana [col 1, col 2],[col row 1, col row 2]
np_2d[[0,1],[0,4]]

array([ 1.73, 68.71])

In [113]:
np_2d[0:2,[1,2,3]]

array([[ 1.68,  1.71,  1.89],
       [59.2 , 63.8 , 88.4 ]])

In [9]:
np_2d[0,1:6]

array([1.68, 1.71, 1.89, 1.79])

In [10]:
np_2d[0:2,1:6]

array([[ 1.68,  1.71,  1.89,  1.79],
       [59.2 , 63.8 , 88.4 , 68.71]])

In [82]:
np_2d

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.2 , 63.8 , 88.4 , 68.71]])