In [1]:
2 < 3

True

In [2]:
'alana' < 'alin'

True

In [3]:
import numpy as np

In [12]:
np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_height

array([1.73, 1.68, 1.71, 1.89, 1.79])

In [13]:
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
np_weight

array([65.4, 59.2, 63.6, 88.4, 68.7])

In [14]:
bmi = np_weight / np_height ** 2
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [15]:
bmi > 23

array([False, False, False,  True, False])

In [16]:
bmi[bmi > 23]

array([24.7473475])