In [1]:
True and True

True

In [2]:
True and False

False

In [3]:
False and True

False

In [4]:
False and False

False

In [5]:
x = 12

In [6]:
x > 5 and x < 15

True

In [7]:
True or True

True

In [8]:
True or False

True

In [9]:
False or True

True

In [10]:
False or False

False

In [11]:
not True

False

In [12]:
not False

True

In [14]:
import numpy as np

In [15]:
np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_height

array([1.73, 1.68, 1.71, 1.89, 1.79])

In [16]:
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
np_weight

array([65.4, 59.2, 63.6, 88.4, 68.7])

In [17]:
bmi = np_weight / np_height ** 2
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [18]:
bmi > 21

array([ True, False,  True,  True,  True])

In [19]:
bmi < 22

array([ True,  True,  True, False,  True])

In [21]:
np.logical_and(bmi > 21, bmi < 22)

array([ True, False,  True, False,  True])

In [22]:
bmi[np.logical_and(bmi>21, bmi<22)]

array([21.85171573, 21.75028214, 21.44127836])