In [1]:
world = {'afganistan':30.55, 'albania':2.77, 'algeria':39.21}
world

{'afganistan': 30.55, 'albania': 2.77, 'algeria': 39.21}

In [3]:
# karena menggunakan dictonary maka menggunakan methode items
for country, population in world.items():
    print(country, '=', population)


afganistan = 30.55
albania = 2.77
algeria = 39.21


In [4]:
import numpy as np

In [5]:
np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_height

array([1.73, 1.68, 1.71, 1.89, 1.79])

In [7]:
np_wight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
np_wight

array([65.4, 59.2, 63.6, 88.4, 68.7])

In [10]:
bmi = np_wight / np_height ** 2
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [11]:
for i in bmi :
    print(i)

21.85171572722109
20.97505668934241
21.750282138093777
24.74734749867025
21.44127836209856


In [13]:
meas = np.array([np_height, np_wight])
meas

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.2 , 63.6 , 88.4 , 68.7 ]])

In [14]:
for i in meas :
    print(i)

[1.73 1.68 1.71 1.89 1.79]
[65.4 59.2 63.6 88.4 68.7]


In [24]:
np.nditer(meas)

In [25]:
for i in np.nditer(meas):
    print(i)

1.73
1.68
1.71
1.89
1.79
65.4
59.2
63.6
88.4
68.7


In [19]:
list = [[65.4, 59.2], [63.6, 88.4], [65.4, 59.2], [63.6, 88.4]]
list

[[65.4, 59.2], [63.6, 88.4], [65.4, 59.2], [63.6, 88.4]]

In [23]:
for i in list :
    print(i)

[65.4, 59.2]
[63.6, 88.4]
[65.4, 59.2]
[63.6, 88.4]


In [37]:
b = []
for i in list:
    b.extend(i)
    print(b)

[65.4, 59.2]
[65.4, 59.2, 63.6, 88.4]
[65.4, 59.2, 63.6, 88.4, 65.4, 59.2]
[65.4, 59.2, 63.6, 88.4, 65.4, 59.2, 63.6, 88.4]


In [38]:
print(b)

[65.4, 59.2, 63.6, 88.4, 65.4, 59.2, 63.6, 88.4]


In [39]:
for i in b:
    print(i)

65.4
59.2
63.6
88.4
65.4
59.2
63.6
88.4
